### ISSUE TITLE
Error on install in VSCode - no release version

### ISSUE THREAD

**Issue by OmarMcAdam** [johnsoncodehk/vue-preview#1]
Error when installing with vscode:

`Can't install release version of 'johnsoncodehk.vscode-vue-preview' extension because it has no release version`

**Comment by johnsoncodehk** [comment]
Try this:
<img width="507" alt="螢幕截圖 2023-02-16 03 27 53" src="https://user-images.githubusercontent.com/16279759/219132364-91aee5ac-0409-45fa-9f17-aa33410513e7.png">

**Comment by OmarMcAdam** [comment]
^^ Works
And I learned something new
